# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: 
      - main
      - issue-*
  pull_request:
    branches: 
      - main
      - issue-*

jobs:
  build_and_test:
    name: Build and Test
    runs-on: macos-latest
    permissions:
      checks: write

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Edge browser
      run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install msedge"
        
    - name: Build with Maven
      run: mvn clean install

    - name: Test Report
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: Test Results
        path: ${{ github.workspace }}/target/surefire-reports/TEST-TestSuite.xml
        reporter: java-junit
        java-version: 17
